pipeline {
    agent any
    environment {
        SONARQUBE_URL = 'http://34.229.218.151:9000/' 
        SONAR_PROJECT_KEY = 'static' 
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/OT-MICROSERVICES/salary-api.git' 
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('demo') { 
                    withCredentials([string(credentialsId: 'static', variable: 'SONARQUBE_TOKEN')]) {
                        sh """
                        mvn sonar:sonar \
                        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                        -Dsonar.host.url=${SONARQUBE_URL} \
                        -Dsonar.token=${SONARQUBE_TOKEN}
                        """
                    }
                }
            }
        }
    }
}
